# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EQEGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eqeWindow(object):
    def setupUi(self, eqeWindow):
        eqeWindow.setObjectName("eqeWindow")
        eqeWindow.resize(898, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/spectrum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        eqeWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(eqeWindow)
        self.centralwidget.setObjectName("centralwidget")
        eqeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(eqeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        eqeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(eqeWindow)
        self.statusbar.setObjectName("statusbar")
        eqeWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(eqeWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(eqeWindow)
        QtCore.QMetaObject.connectSlotsByName(eqeWindow)

    def retranslateUi(self, eqeWindow):
        _translate = QtCore.QCoreApplication.translate
        eqeWindow.setWindowTitle(_translate("eqeWindow", "EQE"))
        self.menuFile.setTitle(_translate("eqeWindow", "File"))
        self.actionQuit.setText(_translate("eqeWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("eqeWindow", "Ctrl+Q"))
import GUI.eqerc
