# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relayWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_relayForm(QtWidgets.QWidget):
    def setupUi(self, relayForm):
        relayForm.setObjectName("relayForm")
        relayForm.resize(94, 222)
        self.gridLayout = QtWidgets.QGridLayout(relayForm)
        self.gridLayout.setObjectName("gridLayout")
        self.oneBox = QtWidgets.QCheckBox(relayForm)
        self.oneBox.setObjectName("oneBox")
        self.gridLayout.addWidget(self.oneBox, 0, 0, 1, 1)
        self.twoBox = QtWidgets.QCheckBox(relayForm)
        self.twoBox.setObjectName("twoBox")
        self.gridLayout.addWidget(self.twoBox, 1, 0, 1, 1)
        self.threeBox = QtWidgets.QCheckBox(relayForm)
        self.threeBox.setObjectName("threeBox")
        self.gridLayout.addWidget(self.threeBox, 2, 0, 1, 1)
        self.fourBox = QtWidgets.QCheckBox(relayForm)
        self.fourBox.setObjectName("fourBox")
        self.gridLayout.addWidget(self.fourBox, 3, 0, 1, 1)
        self.fiveBox = QtWidgets.QCheckBox(relayForm)
        self.fiveBox.setObjectName("fiveBox")
        self.gridLayout.addWidget(self.fiveBox, 4, 0, 1, 1)
        self.sixBox = QtWidgets.QCheckBox(relayForm)
        self.sixBox.setObjectName("sixBox")
        self.gridLayout.addWidget(self.sixBox, 5, 0, 1, 1)

        self.retranslateUi(relayForm)
        QtCore.QMetaObject.connectSlotsByName(relayForm)

    def retranslateUi(self, relayForm):
        _translate = QtCore.QCoreApplication.translate
        relayForm.setWindowTitle(_translate("relayForm", "Form"))
        self.oneBox.setText(_translate("relayForm", "1"))
        self.twoBox.setText(_translate("relayForm", "2"))
        self.threeBox.setText(_translate("relayForm", "3"))
        self.fourBox.setText(_translate("relayForm", "4"))
        self.fiveBox.setText(_translate("relayForm", "5"))
        self.sixBox.setText(_translate("relayForm", "6"))
